parameters:
    env(REDIS_HOST): 'redis'
    env(REDIS_PORT): '6379'

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%'
