version: '3.2'

services:
    php:
        build: ./config/docker/php
        depends_on:
            - db
        volumes:
            - .:/var/www/html
        expose:
            - "9000"
        entrypoint: ./config/docker/docker-entrypoint.sh
    nginx:
        image: 4xxi/nginx:flex
        depends_on:
            - php
        ports:
            - "${SERVER_HTTP_PORT}:80"
        volumes:
            - .:/var/www/html
            - ./var/log:/var/log/nginx
    redis:
        
volumes:
    redis:
