version: '3.2'

services:
    php:
        image: 4xxi/php-redis:php-7.2.2-fpm-alpine3.7
        depends_on:
            - redis
        volumes:
            - .:/var/www/html
        expose:
            - "9000"
        entrypoint: ./config/docker/docker-entrypoint.sh
        environment:
          - REDIS_URL
        networks: 
            - backend  
    nginx:
        image: 4xxi/nginx:flex
        depends_on:
            - php
        ports:
            - "${SERVER_HTTP_PORT}:80"
        volumes:
            - .:/var/www/html
            - ./var/log:/var/log/nginx
        networks: 
            - backend      
    redis:
        image: 'redis:alpine'
        environment:
          # ALLOW_EMPTY_PASSWORD is recommended only for development.
          - ALLOW_EMPTY_PASSWORD=yes
          - REDIS_URL
          - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        # labels:
        #   kompose.service.type: nodeport
        ports:
          - '${REDIS_PORT}:6379'
        networks: 
          - backend    
        volumes:
          - 'redis:/caesarapp/redis'
networks: 
    backend:

volumes:
    redis: