version: '3.2'

services:
    php:
        image: 4xxi/php-redis:php-7.2.2-fpm-alpine3.7
        depends_on:
            - redis
        volumes:
            - .:/var/www/html
        expose:
            - "9000"
        entrypoint: ./config/docker/docker-entrypoint.sh
        environment:
          - REDIS_HOST=redis
          - REDIS_PORT=${REDIS_PORT}
        networks: 
            - backend  
    nginx:
        image: 4xxi/nginx:flex
        depends_on:
            - php
        ports:
            - "${SERVER_HTTP_PORT}:80"
        volumes:
            - .:/var/www/html
            - ./var/log:/var/log/nginx
        networks: 
            - backend      
    redis:
        image: 'redis:alpine'
        environment:
          - REDIS_PORT=${REDIS_PORT}
          - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        networks: 
          - backend    
        volumes:
          - 'redis:/etc/redis/database/caesarapp'
networks: 
    backend:

volumes:
    redis: