version: '3.2'

services:
    php:
        volumes:
            - ./composer.json:/var/www/html/composer.json
            - ./composer.lock:/var/www/html/composer.lock
            - caesarapp-data-sync:/var/www/html:nocopy

volumes:
    caesarapp-data-sync:                                     
        external: true
